// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAdrxhgq-7sxvZR3mgU7qlzdEYNpMBrOo',
    appId: '1:328512272187:web:17461dc56b909c1c44691e',
    messagingSenderId: '328512272187',
    projectId: 'passpilot-6a9e9',
    authDomain: 'passpilot-6a9e9.firebaseapp.com',
    storageBucket: 'passpilot-6a9e9.appspot.com',
    measurementId: 'G-Z4B92KXLL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASddvmutZsXPm9Src1aO4Mrn6x6qCkgWY',
    appId: '1:328512272187:android:146f530b20207ada44691e',
    messagingSenderId: '328512272187',
    projectId: 'passpilot-6a9e9',
    storageBucket: 'passpilot-6a9e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-LscXc6ge3lvSCnnDDzc0ZGplMG8Pos',
    appId: '1:328512272187:ios:ec1128b85ef38d4644691e',
    messagingSenderId: '328512272187',
    projectId: 'passpilot-6a9e9',
    storageBucket: 'passpilot-6a9e9.appspot.com',
    iosClientId: '328512272187-qifuet8b9bi79tt1sdvkmisu13vm5fh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.passpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-LscXc6ge3lvSCnnDDzc0ZGplMG8Pos',
    appId: '1:328512272187:ios:ec1128b85ef38d4644691e',
    messagingSenderId: '328512272187',
    projectId: 'passpilot-6a9e9',
    storageBucket: 'passpilot-6a9e9.appspot.com',
    iosClientId: '328512272187-qifuet8b9bi79tt1sdvkmisu13vm5fh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.passpilot',
  );
}
